default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  host: localhost
  username: pguser
  password: pguser

development:
  <<: *default
  database: police_development_db

test:
  <<: *default
  database: police_test_db

production:
  <<: *default
  database: police_production_db
